name: sds_door_app
description: A new Flutter application.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.0
  firebase_auth: ^0.18.4
  firebase_core: ^0.5.3
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.12+4
  firebase_database: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/


